apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: AT-Liquidacao
spec:
  type: atom-team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "watermark-service"
  description: Serviço de marca dágua
  tags:
    - go
    - microservice
spec:
  type: service
  lifecycle: develop
  owner: AT-Liquidacao
